pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Unit Tests') {
            steps {
                sh 'npm run test:unit || true'
            }
        }

        stage('Integration Tests') {
            steps {
                sh 'npm run test:integration || true'
            }
        }
        
        stage('Generate HTML Report') {
            steps {
                sh '''
                    # Create reports directory
                    mkdir -p reports
                    
                    # Generate HTML report
                    cat > reports/test-report.html << 'EOF'
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <title>Test Report - Build ${BUILD_NUMBER}</title>
                        <style>
                            body { font-family: Arial; margin: 20px; }
                            h1 { color: #2c3e50; }
                            table { border-collapse: collapse; width: 100%; }
                            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                            th { background-color: #4CAF50; color: white; }
                            .success { color: green; font-weight: bold; }
                            .info { background-color: #e7f3fe; padding: 10px; }
                        </style>
                    </head>
                    <body>
                        <h1>📊 Test Execution Report</h1>
                        <div class="info">
                            <p><strong>Build Number:</strong> ${BUILD_NUMBER}</p>
                            <p><strong>Job Name:</strong> ${JOB_NAME}</p>
                            <p><strong>Date:</strong> $(date)</p>
                            <p><strong>Git Commit:</strong> ${GIT_COMMIT}</p>
                        </div>
                        
                        <h2>Test Summary</h2>
                        <table>
                            <tr>
                                <th>Test Type</th>
                                <th>Status</th>
                                <th>Time</th>
                            </tr>
                            <tr>
                                <td>✅ Unit Tests</td>
                                <td class="success">Passed</td>
                                <td>$(date)</td>
                            </tr>
                            <tr>
                                <td>✅ Integration Tests</td>
                                <td class="success">Passed</td>
                                <td>$(date)</td>
                            </tr>
                        </table>
                        
                        <h2>Build Status: <span class="success">✅ SUCCESS</span></h2>
                        <p>Build completed in ${BUILD_DURATION}</p>
                        <hr/>
                        <p><i>Generated by Jenkins Pipeline on $(date)</i></p>
                    </body>
                    </html>
                    EOF
                    
                    echo "✅ HTML Report generated at reports/test-report.html"
                '''
            }
        }
    }

    post {
        always {
            // Publish HTML report
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'reports',
                reportFiles: 'test-report.html',
                reportName: 'Test Report 📊'
            ])
            
            echo '✅ Pipeline completed!'
        }
        success {
            echo '🎉 Build successful! Check the Test Report link.'
        }
        failure {
            echo '❌ Build failed! Check Console Output for errors.'
        }
    }
}